# Generated by Django 5.2.17 on 2026-09-16 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vendorprofile',
            name='unique_matric_number_per_university',
        ),
        migrations.AddConstraint(
            model_name='vendorprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('matric_number__isnull', False), ('is_deleted', False)), fields=('university', 'matric_number'), name='unique_matric_number_per_university'),
        ),
    ]
